# Generated by Django 3.0.2 on 2020-03-18 01:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('programLibrary', '0016_auto_20200202_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a616f911-46d5-40b3-b80b-16b5860f4446'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='id',
            field=models.UUIDField(default=uuid.UUID('89458429-ffce-454b-979a-6cbae6a9c55a'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7f48f1b1-60c6-4777-8404-0917374ab61f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b955a0e3-c82c-4164-9e79-a0254f62421f'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
